export const FETCH_EMPLOYEES = 'FETCH_EMPLOYEES';
export const PHONE_NUMBER_LENGTH_UPDATE = 'PHONE_NUMBER_LENGTH_UPDATE';
export const CREATE_EMPLOYEES = 'CREATE_EMPLOYEES';
export const DELET_EMPLOYEES = 'DELET_EMPLOYEES';
export const EMPLOYEES_SELECTED = 'EMPLOYEES_SELECTED';

export const LOADING_START = 'LOADING_START';
export const LOADING_STOP = 'LOADING_STOP';
